name: next-build.yaml
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 1

      - name: Generate pnpm artifacts lockfile
        uses: ./.github/actions/hermeto
        with:
          image: quay.io/redhat-user-workloads/red-hat-desktop-tenant/extensions-common-nightly:ecbaba34ccca8bf37055ec16d652bfe66712eeda
          args: generate-pnpm-artifacts-lock

      - name: Prefetch pnpm dependencies
        uses: ./.github/actions/hermeto
        with:
          args: fetch-deps pnpm

      - name: Prefetch generic artifacts (pnpm tarball)
        uses: ./.github/actions/hermeto
        with:
          args: fetch-deps generic

      - name: Prefetch generic artifacts (OpenAPI spec)
        uses: ./.github/actions/hermeto
        with:
          args: |
            fetch-deps '{"type": "generic", "path": "openapi"}'

      - name: Inject file modifications
        uses: ./.github/actions/hermeto
        with:
          args: inject-files ./hermeto-output --for-output-dir /tmp/hermeto-output

      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v3
        with:
          image: ${{ github.repository }}
          tags: |
            next
            ${{ github.sha }}
          containerfiles: ./Containerfile
          extra-args: |
            --squash
            --network none
            --volume ${{ github.workspace }}/hermeto-output:/tmp/hermeto-output:Z

      - name: Push Image
        uses: redhat-actions/push-to-registry@v3
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io
