#
# Copyright (C) 2024-2026 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: release

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
      branch:
        description: 'Branch to use for the release'
        required: true
        default: main
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  tag:
    name: Tagging
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    outputs:
      githubTag: ${{ steps.TAG_UTIL.outputs.githubTag}}
      extVersion: ${{ steps.TAG_UTIL.outputs.extVersion}}
      releaseId: ${{ steps.create_release.outputs.id}}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Generate tag utilities
        id: TAG_UTIL
        run: |
            TAG_PATTERN=${{ github.event.inputs.version }}
            echo "githubTag=v$TAG_PATTERN" >> ${GITHUB_OUTPUT}
            echo "extVersion=$TAG_PATTERN" >> ${GITHUB_OUTPUT}

      - name: tag
        run: |
          git config --local user.name ${{ github.actor }}

          # Add the new version in package.json file
          sed -i  "s#version\":\ \"\(.*\)\",#version\":\ \"${{ steps.TAG_UTIL.outputs.extVersion }}\",#g" package.json
          sed -i  "s#version\":\ \"\(.*\)\",#version\":\ \"${{ steps.TAG_UTIL.outputs.extVersion }}\",#g" packages/backend/package.json
          sed -i  "s#version\":\ \"\(.*\)\",#version\":\ \"${{ steps.TAG_UTIL.outputs.extVersion }}\",#g" packages/frontend/package.json
          sed -i  "s#version\":\ \"\(.*\)\",#version\":\ \"${{ steps.TAG_UTIL.outputs.extVersion }}\",#g" packages/shared/package.json
          git add package.json
          git add packages/backend/package.json
          git add packages/frontend/package.json
          git add packages/shared/package.json

          # commit the changes
          git commit -m "chore: 🥁 tagging ${{ steps.TAG_UTIL.outputs.githubTag }} 🥳"
          echo "Tagging with ${{ steps.TAG_UTIL.outputs.githubTag }}"
          git tag ${{ steps.TAG_UTIL.outputs.githubTag }}
          git push origin ${{ steps.TAG_UTIL.outputs.githubTag }}

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.TAG_UTIL.outputs.githubTag }}
          name: ${{ steps.TAG_UTIL.outputs.githubTag }}
          draft: true
          prerelease: false

      # - name: Create the PR to bump the version in the main branch (only if we're tagging from main branch)
      #   if: ${{ github.event.inputs.branch == 'main' }}
      #   run: |
      #     git config --local user.name ${{ github.actor }}
      #     CURRENT_VERSION=$(echo "${{ steps.TAG_UTIL.outputs.extVersion }}")
      #     tmp=${CURRENT_VERSION%.*}
      #     minor=${tmp#*.}
      #     bumpedVersion=${CURRENT_VERSION%%.*}.$((minor + 1)).0
      #     bumpedBranchName="bump-to-${bumpedVersion}"
      #     git checkout -b "${bumpedBranchName}"
      #     sed -i  "s#version\":\ \"\(.*\)\",#version\":\ \"${bumpedVersion}-next\",#g" package.json
      #     sed -i  "s#version\":\ \"\(.*\)\",#version\":\ \"${bumpedVersion}-next\",#g" packages/backend/package.json
      #     sed -i  "s#version\":\ \"\(.*\)\",#version\":\ \"${bumpedVersion}-next\",#g" packages/frontend/package.json
      #     sed -i  "s#version\":\ \"\(.*\)\",#version\":\ \"${bumpedVersion}-next\",#g" packages/shared/package.json
      #     git add package.json
      #     git add packages/backend/package.json
      #     git add packages/frontend/package.json
      #     git add packages/shared/package.json
      #     git commit -s --amend -m "chore: bump version to ${bumpedVersion}"
      #     git push origin "${bumpedBranchName}"
      #     echo -e "📢 Bump version to ${bumpedVersion}\n\n${{ steps.TAG_UTIL.outputs.extVersion }} has been released.\n\n Time to switch to the new ${bumpedVersion} version 🥳" > /tmp/pr-title
      #     pullRequestUrl=$(gh pr create --title "chore: 📢 Bump version to ${bumpedVersion}" --body-file /tmp/pr-title --head "${bumpedBranchName}" --base "main")
      #     echo "📢 Pull request created: ${pullRequestUrl}"
      #     echo "➡️ Flag the PR as being ready for review"
      #     gh pr ready "${pullRequestUrl}"
      #     echo "🔅 Mark the PR as being ok to be merged automatically"
      #     gh pr merge "${pullRequestUrl}" --auto --rebase
      #     git checkout ${{ steps.TAG_UTIL.outputs.githubTag }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PODMAN_DESKTOP_BOT_TOKEN }}

  build-oci:
    needs: [tag]
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    outputs:
      artifact-id: ${{ steps.build-oci.outputs.artifact-id }}
    steps:
      - uses: podman-desktop/gh-extensions-actions/.github/actions/oci-build@19efb8f2422c54ad8904ad068ad363bcabaacc96 # v0.1.0
        name: build-oci
        id: build-oci
        with:
          image-name: '${{ github.repository }}'
          ref: ${{ needs.tag.outputs.githubTag }}

  publish-oci:
    needs: [tag, build-oci]
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: podman-desktop/gh-extensions-actions/.github/actions/oci-publish@19efb8f2422c54ad8904ad068ad363bcabaacc96 # v0.1.0
        name: publish-oci
        with:
          image-name: '${{ github.repository }}'
          registry: 'ghcr.io'
          registry-username: ${{ github.repository_owner }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.tag.outputs.extVersion }} latest
          artifact-id: ${{ needs.build-oci.outputs.artifact-id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.run_id }}

  release:
    needs: [tag, publish-oci]
    name: Release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: id
        run: echo the release id is ${{ needs.tag.outputs.releaseId}}

      - name: Publish release
        uses: StuYarrow/publish-release@01f2a1365bacd77bad861873a7fdf274ab49eefd # v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ needs.tag.outputs.releaseId}}
